### ISSUE TITLE
Error when running Script

### ISSUE THREAD

**Issue by UliAbo** [Tsukina-7mochi/aseprite-scripts#5]
Hey there, 
Thanks for this script! I just tried it out and run it, then the following error message comes:

Could you help me?

![image](https://user-images.githubusercontent.com/1249266/116558125-66d08300-a8ff-11eb-8164-6da5de067c7d.png)

Thanks,
Abo

**Comment by Tsukina-7mochi** [comment]
Hello,  
You seems to downloaded project page(.html), not script(.lua), so try open raw code then hit ctrl-s to save raw script.

![image](https://user-images.githubusercontent.com/60507815/116568690-a4ef9600-a943-11eb-9ed3-ec2ca64145c1.png)

Thank you for using my script.

**Comment by UliAbo** [comment]
Ah yes! That was my mistake. Now it works. Thanks for the quick reply.
Works like a charm!
